### ISSUE TITLE
evaluate.py

### ISSUE THREAD

**Issue by ovidov** [calmiLovesAI/ComputerVision.pytorch#1]
why in YOLOv8 doesn't have evaluate_on_voc which make error happen in enaluate.py on line 32?

**Comment by calmiLovesAI** [comment]
> why in YOLOv8 doesn't have evaluate_on_voc which make error happen in enaluate.py on line 32?

It has been fixed.

**Comment by ovidov** [comment]
> 

感謝，我發現只要修改yolov7的evaluate_on_voc的code，yolov8就可以使用了，不好意思麻煩up主了，感謝。

**Comment by calmiLovesAI** [comment]
> > 
> 
> 感謝，我發現只要修改yolov7的evaluate_on_voc的code，yolov8就可以使用了，不好意思麻煩up主了，感謝。

嗯嗯，我也是直接修改的yolo7的验证代码
